services:
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    #command: bash -c "rails db:create && rails db:migrate && rails db:seed"
    ports:
      - "4000:3000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"